/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.example.Controller.FileManagerController;

public class App {
    public String getGreeting() {


        FileManagerController controller = new FileManagerController();
        controller.mkdir("/project/hello-world/app.js");
        controller.updateFile("/project/hello-world/app.js", "console.log('Hello, World!');");

        controller.mkdir("/project/lld");
        controller.newFile("/project/lld/main.cpp", "int main() { return 0; }");

        controller.ls("/project/");
        controller.rmdir("/project/lld");
        controller.ls("/project/");
        controller.echo("/project/hello-world/app.js");
        controller.rmfile("/project/hello-world/app.js");
        controller.ls("/project/hello-world/");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
